# Generated by Django 5.1.6 on 2025-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(max_length=200)),
                ('shipping_last_name', models.CharField(max_length=200)),
                ('shipping_phone_no', models.CharField(max_length=15)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_zipcode', models.IntegerField()),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
