# Generated by Django 5.1.6 on 2025-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billing_created_at_billing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='shipping_zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
