# Generated by Django 5.2.4 on 2025-07-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
