# Generated by Django 5.2.4 on 2025-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
