# Generated by Django 5.2.4 on 2025-07-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_register_gender_alter_register_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
