# Generated by Django 5.1.6 on 2025-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
