# Generated by Django 5.1.6 on 2025-07-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_class',
        ),
    ]
