# Generated by Django 5.1.6 on 2025-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
