# Generated by Django 5.1.6 on 2025-07-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
